server:
  port: 8888

management:
  server:
    port: ${MANAGEMENT_PORT:8889}

spring:
  cloud:
    config:
      server:
        encrypt:
          enabled: false
  security:
    basic:
      enabled: false